# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('img', models.FileField(upload_to='media/slider')),
                ('link', models.CharField(default='/', max_length=100)),
                ('name', models.CharField(default='\u0421\u043b\u0430\u0439\u0434\u0435\u0440 \u2116', max_length=50)),
            ],
        ),
    ]
