# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscorp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_page', models.CharField(default='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0438 \u043e\u0431\u0449\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f', max_length=50)),
                ('phone', models.CharField(default='+7 (495) 968 77 43', max_length=20)),
                ('email', models.CharField(default='ae@presscorp.ru', max_length=30)),
                ('adress', models.CharField(default='\u0410\u0434\u0440\u0435\u0441: \u0433. \u041c\u043e\u0441\u043a\u0432\u0430, \u0443\u043b. \u041d\u0430\u0433\u0430\u0442\u0438\u043d\u0441\u043a\u0430\u044f, 3\u0430', max_length=150)),
                ('vk', models.CharField(default='https://vk.com/presscorp', max_length=100)),
                ('fb', models.CharField(default='https://www.facebook.com/PressCorp/', max_length=100)),
                ('insta', models.CharField(default='https://www.instagram.com/presscorp/', max_length=100)),
            ],
            options={
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
            },
        ),
    ]
